apiVersion: skaffold/v2beta6
kind: Config
deploy:
  helm:
    releases:
      - name: divan
        chartPath: .\infra\helm\
        valuesFiles:
          - .\infra\helm\values.yaml
        artifactOverrides:
          image: cubrenig/pgwasdivan

build:
  local:
    push: false
    concurrency: 5
  artifacts:
    - image: cubrenig/pgwasdivan
      context: app
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
          - src: "**/*.R"
            dest: .
          - src: "**/*.sh"
            dest: .